name: food_recipes
description: Food Recipes - Flutter Submission 1

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/breakfast/donat_maizena.jpg
    - assets/images/breakfast/rolade_tahu_bayam.jpg
    - assets/images/breakfast/pancake_mangga_beku.jpg
    - assets/images/breakfast/tahu_pok_pok_krispi_renyah.jpg
    - assets/images/breakfast/samosa.jpg
    - assets/images/breakfast/nasi_bakar_tuna.jpg
    - assets/images/breakfast/kupat_tahu.jpg
    - assets/images/breakfast/es_pisang_ijo.jpg
    - assets/images/breakfast/gulai_lidah_sapi.jpg
    - assets/images/breakfast/capcay_jamur_saus_tiram.jpg
    - assets/images/breakfast/asem_asem_daging.jpg
    - assets/images/breakfast/sup_iga_kambing.jpg
    - assets/images/breakfast/tahu_lada_hitam.jpg
    - assets/images/breakfast/tahu_walik_aci.jpg
    - assets/images/breakfast/tumis_ayam_sayuran.jpg
    - assets/images/breakfast/tumis_tahu_goreng_teriyaki.jpg

    - assets/images/dessert/apem_pandan.jpg
    - assets/images/dessert/cookies_choco_chips.jpg
    - assets/images/dessert/cookies_choco_pandan.jpg
    - assets/images/dessert/cookies_cokelat.jpg
    - assets/images/dessert/dragon_sticky_rice.jpg
    - assets/images/dessert/ketan_lapis_sarikaya.jpg
    - assets/images/dessert/klappertaart_kukus.jpg
    - assets/images/dessert/nagasari.jpg
    - assets/images/dessert/pisang_goreng_lapis_kelapa_muda.jpg
    - assets/images/dessert/ropang_isi_apel.jpg
    - assets/images/dessert/ropang_isi_pisang.jpg
    - assets/images/dessert/roti_jala_durian.jpg
    - assets/images/dessert/serabi_manis.jpg
    - assets/images/dessert/sop_buah_yogurth.jpg
    - assets/images/dessert/srikaya_roti_tawar.jpg
    - assets/images/dessert/ubi_goreng_lapis_kelapa.jpg


    - assets/breakfast.json
    - assets/desert.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Regular.ttf